// <auto-generated />
using System;
using HumanResources.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResources.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeSeniority")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EmploymentStartDate")
                        .HasColumnType("date");

                    b.Property<int>("HcmEmployeeRoleEntityId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlySalaryFixed")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MonthlySalaryVariable")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("HcmEmployeeRoleEntityId");

                    b.ToTable("EmployeeEntities");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.HcmEmployeeRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HcmEmployeeRoleEntities");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.HcmPersonDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeEntityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeEntityId")
                        .IsUnique();

                    b.ToTable("HcmPersonDetailEntities");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.EmployeeEntity", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Employees.HcmEmployeeRoleEntity", "HcmEmployeeRoleEntity")
                        .WithMany("Employees")
                        .HasForeignKey("HcmEmployeeRoleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HcmEmployeeRoleEntity");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.HcmPersonDetailEntity", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Employees.EmployeeEntity", "EmployeeEntity")
                        .WithOne("HcmPersonDetailEntity")
                        .HasForeignKey("HumanResources.Domain.Entities.Employees.HcmPersonDetailEntity", "EmployeeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeEntity");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.EmployeeEntity", b =>
                {
                    b.Navigation("HcmPersonDetailEntity");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employees.HcmEmployeeRoleEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
